### ISSUE TITLE
Import problem from yosai_alchemystore models

### ISSUE THREAD

**Issue by canberkkoc** [YosaiProject/monster_rx#1]
Hello All,

I am trying to run demo as described at readme but i have : 

> ImportError: cannot import name 'CredentialModel'

 When i look at yosai_alchemystore code i saw model name is  'Credential' not 'CredentialModel'. Am i doing something wrong or there is a typo at init_yosai_db.py

**Comment by the-mann** [comment]
I am having the same problem, did you ever figure it out?

**Comment by MacCruiskeen** [comment]
I've almost got this working, but not quite. As you noticed, the names imported are not the names in the actual module. You have to change that. I imported the module with an alias so I could use namespaced referrals, but it was still necessary to rename the application's User to something else.Then, once you actually get the db initialization script to run, you have to create a configuration file for Yosai and pass the created db as an argument to the init_engine() in the other script. So I've got it to the point where it will start, and call the login form, but it fails with an error while trying to create th form. I get 

TypeError: __init__() got an unexpected keyword argument 'encoders'

when it tries to execute

CBOREncoder(fp, **kwargs).encode(obj)

There appears to be something wrong with the formatting of the kwargs being passed, but I haven't been able to figure it out. 

Also, note the Yosai_Pyramid login forms are created with wtforms 2.1, which could be an issue if mixed into an application using wtforms 3.0, which no longer has extensions. 

I was hoping I could figure out how to get this working, since it seems to have all the features I need for my project, but I'm close to giving up.
